repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
  - id: name-tests-test
  - id: requirements-txt-fixer
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
  - id: mypy
- repo: local
  hooks:
  - id: black
    name: black
    entry: black
    language: system
    types: [ python ]
    files: ^(orbital|tests)
  - id: isort
    name: isort
    entry: isort
    language: system
    types: [ python ]
    files: ^(orbital|tests)
  - id: flake8
    name: flake8
    entry: flake8
    language: system
    types: [ python ]
    files: ^(orbital|tests)
